#!/usr/bin/env bash
# displays a phrase constantly while
#+ sleeping for 2 at each display
# displays an additional sentence in between

while true
do
		echo "To infinity and beyond"
		sleep 2
		trap 'echo "I am invincible!!!"' SIGTERM
done
