#!/usr/bin/env bash
# Script parses apache log files in list format
#groups by IP and HTTP status code.
#displays the number of occurences, IP and HTTP status
# sorts the code log

file="apache-access.log"
awk -F ' ' '{ print $1, $9}' $file | sort | uniq -c | sort -nr