#!/usr/bin/env bash
# displays Best School 10 times and just before the 10th, says hi.

index=1

while [ $index -le 10 ]
do
    echo "Best School"
    if [ $index -eq 9 ]
    then
        echo "HI"
    fi
    ((index++))
done