#!/usr/bin/env bash
# script loops through 1 to 10.
# prints 'Best School' for each iteration
# prints 'bad luck' for 4
# prints 'good luck' for 8

index=1

while [ $index -le 10 ]
do
    if [ $index -eq 4 ]
    then
        echo "bad luck"
    elif [ $index -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((index++))
done