#!/usr/bin/env bash
# This script prints using 12hr clock
# prints hours from 0 to 12
# prints minutes from 1 to 59

hrs = 0

while [ $hrs -le 12 ]
do
    echo "Hour: $hrs"
    mins = 1
    while [ $mins -le 59 ]
    do
        echo "$mins"
        (( mins++ ))
    done
    (( hrs++ ))
done
