#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash

list1=$(ls)

for i in $list1; do
    echo "$i" | cut -d '-' -f2
done